backend:
  name: git-gateway
  branch: main
  site_domain: cms.netlify.com
local_backend: true
media_folder: static/img
public_folder: /img
collections:
  #BLOG
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "Blog"
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "index"
    path: "{{path}}/index"
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Link w Wyszukiwarce",
          name: "path",
          widget: "string",
          required: true,
          hint:
            "Jest to unikalna nazwa dla podstrony z blogiem, zapoznaj się z instrukcją:
            1.NIE MOŻNA UŻYWAĆ POLSKICH ZNAKÓW,
            2.ZAMIAST SPACJI MYŚLNIKI,
            3.NIE UŻYWAĆ ZNAKÓW SPECJALNYCH,
            4.PO OPUBLIKOWANIU BLOGA NIE ZEMINIAĆ W PRZYSZŁOŚCI,(jeśli zostało zmienione, zmienić nazwę pliku .md w folderze /content/blog na taką jaką podało się w polu),
            5.Przykład: wyjscie-z-psem-na-spacer ",
        }
